import * as dotenv from 'dotenv';
dotenv.config();

export default {
  MAIN_SEARCH_URL: process.env.MAIN_SEARCH_URL,
  SEARCH_BAR_DOM_SELECTOR: process.env.SEARCH_BAR_DOM_SELECTOR,
  SEARCH_BTN_DOM_SELECTOR: process.env.SEARCH_BTN_DOM_SELECTOR,
  TOTAL_COUNT_DOM_SELECTOR: process.env.TOTAL_COUNT_DOM_SELECTOR,
  STORE_NAME_LINK_DOM_SELECTOR: process.env.STORE_NAME_LINK_DOM_SELECTOR,
  STORE_DETAIL_DOM_NAME: process.env.STORE_DETAIL_DOM_NAME,
  PAGINATION_DOM_SELECTOR: process.env.PAGINATION_DOM_SELECTOR,
  STORE_DETAIL_TABLE_SELECTOR: process.env.STORE_DETAIL_TABLE_SELECTOR,
  EMAIL_DOM_SELECTOR: process.env.EMAIL_DOM_SELECTOR,
};
